## numpy数组运算

## 1.4.1 算术运算

* add 加
* subtract 减
* multiple 乘
* divide 除

## 1.4.2 数学运算

* 三角函数：sin、cos、tan
* 算术运算

## 1.4.3 统计运算

* mean 均值
* average 均值
* var 方差
* std 标准差

## 1.4.4 聚合运算

* 性能区别：np聚合函数 vs py内置函数
* sum 累加
* prod 累乘
* max 最大值
* min 最小值
* 统计运算

## 1.4.5 筛选与排序

* where函数
* sort函数

In [13]:
import numpy as np

arr1 = np.array([1, 2, 3, 4], float)
arr2 = np.array([5, 6, 7, 8], float)

res1 = np.add(arr1, arr2)
print(res1)
np.subtract(arr2, arr1)
np.multiply(arr1, arr2)
np.divide(arr2, arr1)



[ 6.  8. 10. 12.]


array([5.        , 3.        , 2.33333333, 2.        ])

In [20]:
ang = np.array([0, 30, 37, 45, 60, 90])
rad = np.sin(ang * np.pi / 180)
rad = np.cos(ang * np.pi / 180)
rad = np.tan(ang * np.pi / 180)
rad

array([0.00000000e+00, 5.77350269e-01, 7.53554050e-01, 1.00000000e+00,
       1.73205081e+00, 1.63312394e+16])

In [26]:
arr1 = np.array([5, 6, 7, 8, 9])
arr1.mean()
np.average(arr1)
np.var(arr1)  # 方差
np.std(arr1)  # 标准差

1.4142135623730951

In [30]:
arr1 = np.array([5, 6, 7, 8, 9])
np.sum(arr1)  # 35
np.prod(arr1)  # 15120
np.max(arr1)  # 9
np.min(arr1)  # 5

5

In [39]:
arr1 = np.array([5, 6, 7, 8, 9])
np.where(arr1 > 6)[0]
np.sort(arr1)


array([5, 6, 7, 8, 9])