# 矩阵运算


In [31]:
import numpy as np

a = np.arange(15).reshape(3, 5)
b = np.arange(15, 30).reshape(3, 5)
c = np.array([9, 8, 7, 6])

print(a)
print(b)
print(c)

a+b

2*a

a = a.T
np.dot(a,c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[9 8 7 6]


ValueError: shapes (5,3) and (4,) not aligned: 3 (dim 1) != 4 (dim 0)